CREATE TABLE CUSTOMERS (
USERNAME Varchar2 NOT NULL,
NAME VARCHAR2 NOT NULL,
ADDRESS VARCHAR2 NOT NULL,
CREDITCARDDETAILS VARCHAR NOT NULL,
PASSWORD VARCHAR2 NOT NULL,
EMAIL VARCHAR2 NOT NULL,
CONSTRAINT PK_CUSTOMERS PRIMARY KEY(USERNAME)
)