CREATE TABLE products (
ID INTEGER NOT NULL,
NAME VARCHAR NOT NULL,
DESCRIPTION VARCHAR NOT NULL,
CATEGORY VARCHAR NOT NULL,
PRICE FLOAT NOT NULL,
QUANTITY INTEGER NOT NULL,
CONSTRAINT PK_PRODUCTS PRIMARY KEY(ID)
);
